# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      # focal
      # https://docs.travis-ci.com/user/reference/focal/
      - python: 3.9
        dist: focal
        sudo: true
        env: TOX_ENV=py39
      - python: 3.8
        dist: focal
        sudo: true
        env: TOX_ENV=py38
      - python: 3.7
        dist: focal
        sudo: true
        env: TOX_ENV=py37
      - python: 3.7
        dist: focal
        sudo: true
        env: TOX_ENV=lint
      # bionic
      # https://docs.travis-ci.com/user/reference/bionic/
      - python: 3.9
        dist: bionic
        sudo: true
        env: TOX_ENV=py39
      - python: 3.8
        dist: bionic
        sudo: true
        env: TOX_ENV=py38
      - python: 3.7
        dist: bionic
        sudo: true
        env: TOX_ENV=py37
      - python: 3.7
        dist: bionic
        sudo: true
        env: TOX_ENV=lint
      # xenial
      # https://docs.travis-ci.com/user/reference/xenial/
      - python: 3.7
        dist: xenial
        sudo: true
        env: TOX_ENV=py37
      - python: 3.7
        dist: xenial
        sudo: true
        env: TOX_ENV=lint

install:
  - pip install tox
  - pip install .

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
